// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyirsj1A4MK3h-8dnNVaF3n9-DB1bN5UA',
    appId: '1:923854126643:ios:4cddf432d4c1c211f62d46',
    messagingSenderId: '923854126643',
    projectId: 'my-ecommerce-app-17a7c',
    storageBucket: 'my-ecommerce-app-17a7c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyirsj1A4MK3h-8dnNVaF3n9-DB1bN5UA',
    appId: '1:923854126643:ios:4cddf432d4c1c211f62d46',
    messagingSenderId: '923854126643',
    projectId: 'my-ecommerce-app-17a7c',
    storageBucket: 'my-ecommerce-app-17a7c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkNLRV1_Sa1H8Cz0jDnEan8sziLt56Z3I',
    appId: '1:923854126643:web:5a9156e6e0910a6ef62d46',
    messagingSenderId: '923854126643',
    projectId: 'my-ecommerce-app-17a7c',
    authDomain: 'my-ecommerce-app-17a7c.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-17a7c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkNLRV1_Sa1H8Cz0jDnEan8sziLt56Z3I',
    appId: '1:923854126643:web:5a9156e6e0910a6ef62d46',
    messagingSenderId: '923854126643',
    projectId: 'my-ecommerce-app-17a7c',
    authDomain: 'my-ecommerce-app-17a7c.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-17a7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5FYCZEeDd707rZhkNfGm9ZMnkKw60TOQ',
    appId: '1:923854126643:android:e6acc362bc197706f62d46',
    messagingSenderId: '923854126643',
    projectId: 'my-ecommerce-app-17a7c',
    storageBucket: 'my-ecommerce-app-17a7c.firebasestorage.app',
  );

}